In [1]:
import numpy as np
import itertools
from itertools import permutations
combos = []
featureList = [1,2,3]
dataNrs = np.arange(len(featureList))

maxCombinationAmount = 1
if maxCombinationAmount > len(dataNrs):
    maxCombinationAmount = len(dataNrs)
for L in range(1, maxCombinationAmount  + 1):
            for subsetNr in itertools.combinations(dataNrs, L):
                combos.append(subsetNr)

In [3]:
h = "hell"
g = "hel"
if g == h:
    print("gsd")

In [3]:
import dask
import numpy

@dask.delayed
def jopp(y):
    print("oy")
    return y*y

@dask.delayed
def hopp(x):
    print("oka")
    return [jopp(x+1), jopp(x+2), jopp(x+3)]

listList = []
for h in range(3):
    listList.append(hopp(h))
    
print(listList)
compList = dask.compute(listList)
comp = dask.compute(compList)
print(compList)
print(listList)
#print(comp)



[Delayed('hopp-390566ba-ff91-465e-8db1-f7e2ec84dda6'), Delayed('hopp-1523bb28-eba4-4b3f-82ca-f6caf805fc19'), Delayed('hopp-aff0964c-5718-4605-be61-f04c89d2becf')]
oka
oka
oka
oy
oy
oy
oy
oy
oy
oy
oy
oy
([[Delayed('jopp-e334dee7-c423-4c80-b265-127c71a8381e'), Delayed('jopp-6ddd8c6b-7f5f-4d95-9c51-74676b572517'), Delayed('jopp-79da7995-ade2-4035-a335-a1d3fcad46f8')], [Delayed('jopp-50d48bfc-b2c0-45be-a3dd-3e5e3e035963'), Delayed('jopp-efda70c7-fe8a-4fa0-b77e-6a7d27d465c6'), Delayed('jopp-cfe2bf12-73e8-42d6-8eb7-1720b544d66c')], [Delayed('jopp-ca0fa27d-335c-4140-8671-474a6cadc541'), Delayed('jopp-1d578fd0-755a-4868-8a49-5e632c2cdcc6'), Delayed('jopp-833748dd-417b-4f63-a92c-cb966a13613a')]],)
[Delayed('hopp-390566ba-ff91-465e-8db1-f7e2ec84dda6'), Delayed('hopp-1523bb28-eba4-4b3f-82ca-f6caf805fc19'), Delayed('hopp-aff0964c-5718-4605-be61-f04c89d2becf')]


In [17]:
import numpy as np
nfp = np.zeros([3,3])

nfp[1,2] = 2
nfp[2,1] = 2
print(nfp)
ind = np.where(nfp>1)[1]
print(np.where(nfp>1)[1])
nfp[ind]

[[0. 0. 0.]
 [0. 0. 2.]
 [0. 2. 0.]]
[2 1]


array([[0., 2., 0.],
       [0., 0., 2.]])

In [5]:
def insert_cn(string, index):
    return string[:index] + f'cn{6}' + string[index:]
    

h = "fftDataBC"
print(insert_cn(h, -2))

fftDatacn6BC


In [17]:
import numpy as np
h = np.zeros([10,120,2])
print(h.shape)
h = np.reshape(h, [h.shape[0],-1])
print(h.shape)


(10, 120, 2)
(10, 240)


In [12]:

h = np.ones([10,307])
print(h.shape)
while True:
    if h.shape[1] % 13 != 0:
        h = h[:,:-1]
    else:
        break
print(h.shape)

(10, 307)
(10, 299)


In [66]:
b = np.array([ 1 , 0, 6, 4] ) 
c = np.array([ 1 , 0, 0, 4] )
#np.where( b == 2)[0]
#any([any(b==3), any(b==4)])

#any([True, False])
#np.where(b == 3 or b == 4)
[b != 0][0] + [c!=0 ][0]

array([ True, False,  True,  True])

In [13]:
import numpy as np
a = np.array([0,1,0,3])
c = np.array([5,1,2,3])

b = c[np.where(a != 0)[0]]
b

array([1, 3])

In [35]:
maxCombinationAmount = 6
combos2 = []
if maxCombinationAmount > len(dataNrs):
    maxCombinationAmount = len(dataNrs)
for x in range(1,maxCombinationAmount+1):
    combos2.extend(list(itertools.permutations(dataNrs, x)))
print(combos2)


[(0,), (1,), (2,), (0, 1), (0, 2), (1, 0), (1, 2), (2, 0), (2, 1), (0, 1, 2), (0, 2, 1), (1, 0, 2), (1, 2, 0), (2, 0, 1), (2, 1, 0)]


In [36]:
combos

[(0,), (1,), (2,), (0, 1), (0, 2), (1, 2), (0, 1, 2)]